# Generated by Django 6.0.4 on 2026-04-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=20)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factures.facture')),
            ],
        ),
    ]
